name: Checks
on:
  push:
  # pull_request:
  #   branches:
  #     - main

env:
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: password
  DATABASE_CONNECTION_URL: "postgresql+asyncpg://postgres:password@localhost:5432/test"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: 24.4.2

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - uses: isort/isort-action@master
        with:
          isortVersion: 5.13.2
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - run: poetry run ruff check .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: test
        run: |
          poetry run pytest
